In [8]:
from arbitrum_gatherer.config import DATABASE_CRED,DATABASE, DATABASE_HOSTNAME
import pandas as pd

In [5]:
from clickhouse_driver import Client
chClient = Client(
        DATABASE_HOSTNAME,
        user="admin",
        password=DATABASE_CRED,
        port=9440,
        secure="y",
        verify=False,
        database=DATABASE,
    )
sql = f'''
select * from {DATABASE}.demo_table
'''
chClient.execute(sql)

[]

In [3]:
sql = f'''
CREATE TABLE IF NOT EXISTS {DATABASE}.blocks_raw
(
    hash String,
    number Int64,
    parent_hash String,
    nonce String,
    sha3_uncles String,
    logs_bloom String,
    transactions_root String,
    state_root String,
    receipts_root String,
    miner String,
    difficulty Int64,
    total_difficulty Int64,
    size Int64,
    extra_data String,
    gas_limit Int64,
    gas_used Int64,
    timestamp DateTime,
    transaction_count Int32,
    l1_block_number String,
    mix_hash String
)
ENGINE = MergeTree
PRIMARY KEY (number,hash)
ORDER BY (number, hash)
'''
chClient.execute(sql)

[]

In [4]:
sql = f'''
CREATE TABLE IF NOT EXISTS {DATABASE}.transactions_raw
(
    hash String,
    nonce Int64,
    block_hash String,
    block_number Int64,
    transaction_index Int32,
    from_address String,
    to_address String,
    value Int64,
    gas Int64,
    gas_price Int64,
    input String,
    block_timestamp DateTime
    
)
ENGINE = MergeTree
PRIMARY KEY (block_number,hash)
ORDER BY (block_number, hash)
'''
chClient.execute(sql)

[]

In [22]:
sql = '''
select * from yarkin_arbitrum.blocks_raw
'''
query_result, columns = chClient.execute(sql,with_column_types=True)
df = pd.DataFrame(query_result,columns=[tuple[0] for tuple in columns])
df

,hash,number,parent_hash,nonce,sha3_uncles,logs_bloom,transactions_root,state_root,receipts_root,miner,difficulty,total_difficulty,size,extra_data,gas_limit,gas_used,timestamp,transaction_count,l1_block_number,mix_hash
0,0x7ee576b35482195fc49205cec9af72ce14f003b9ae69...,0,0x00000000000000000000000000000000000000000000...,0x0000000000000000,,0x00000000000000000000000000000000000000000000...,0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996c...,0x00000000000000000000000000000000000000000000...,0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996c...,0x0000000000000000000000000000000000000000,0,0,505,0x,288000000,0,1970-01-01 00:00:00,0,0x0,0x00000000000000000000000000000000000000000000...
1,0xe0594250efac73640aeff78ec40aaaaa87f91edb54e5...,1,0x7ee576b35482195fc49205cec9af72ce14f003b9ae69...,0x0000000000000000,,0x00000000000000000000000000000000000000000000...,0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996c...,0x00000000000000000000000000000000000000000000...,0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996c...,0x0000000000000000000000000000000000000000,0,0,509,0x,288000000,0,2021-05-28 23:09:04,0,0x0,0x00000000000000000000000000000000000000000000...
2,0xb19bba5e4d767c845f1719a9e4b0a1e80b47db90c52c...,2,0xe0594250efac73640aeff78ec40aaaaa87f91edb54e5...,0x0000000000000000,,0x00000000000000000000000000000000000000000000...,0x48b1bc900cf22ce6c5f6cfdfd4a17ebc5229936ed97b...,0x00000000000000000000000000000000000000000000...,0x1060d928de10aef424bf33eaa6740f39a131e014e80f...,0x0000000000000000000000000000000000000000,0,0,689,0x,287985032,121,2021-05-29 00:35:11,1,0xbf21fa,0x00000000000000000000000000000000000000000000...
3,0x5b7be82ae165c66bdf727c54822ef9023440d4750e8a...,3,0xb19bba5e4d767c845f1719a9e4b0a1e80b47db90c52c...,0x0000000000000000,,0x00000000000000000000000000000000000000000000...,0x8b590f744b164106b7dd408d5343d04a1942c76d8e00...,0x00000000000000000000000000000000000000000000...,0x9d513f12aa621bc9c7be76593ae4d69742ff8268f2a2...,0x0000000000000000000000000000000000000000,0,0,722,0x,287994892,123,2021-05-29 01:02:54,1,0xbf2272,0x00000000000000000000000000000000000000000000...
4,0xa4e36737b18e5ffc517fa7cc2cdc28f82767f8f5a0c8...,4,0x5b7be82ae165c66bdf727c54822ef9023440d4750e8a...,0x0000000000000000,,0x00000000000000000000000000000000000000000000...,0x09290b2de4a6e658276ee292665dc6f16f1212ef3c82...,0x00000000000000000000000000000000000000000000...,0x502ab6b104f11aa3a3554ce4029e9e17fafc7ee1409b...,0x0000000000000000000000000000000000000000,0,0,723,0x,287995941,133,2021-05-29 01:05:59,1,0xbf227e,0x00000000000000000000000000000000000000000000...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99996,0x61924205b32d0394c7f7e2a698083e54d4ceee87b0e5...,99996,0x9eca332df26b336f058eea98b26ce50f79f8884344f4...,0x0000000000000000,,0x00000000000000000000000000000000000000000000...,0x3fb0e7889e75cfe6e6e71d90354e8f21369a3be07a18...,0x00000000000000000000000000000000000000000000...,0x944ac65245d4c2822e37a14368227d47e87d5140a252...,0x0000000000000000000000000000000000000000,0,0,1320,0x,287956567,3736,2021-07-12 15:58:35,1,0xc3843c,0x00000000000000000000000000000000000000000000...
99997,0x6480d83c4a1e1384db0341e87d0395aa5be34a724a65...,99997,0x61924205b32d0394c7f7e2a698083e54d4ceee87b0e5...,0x0000000000000000,,0x00000000000000000000000000000000000000000000...,0xb48827297e43e0ba39fbdc5e1f17d29f0450498086ec...,0x00000000000000000000000000000000000000000000...,0xb1b5641b75a4646a371586cf89405f00efef52e55f2e...,0x0000000000000000000000000000000000000000,0,0,1320,0x,287990643,3736,2021-07-12 16:00:13,1,0xc38440,0x00000000000000000000000000000000000000000000...
99998,0x0fe4523a2ebf1fe3428e4959e53572f7a60cfcf79460...,99998,0x6480d83c4a1e1384db0341e87d0395aa5be34a724a65...,0x0000000000000000,,0x00000000000000000000000000000000000000000000...,0xfe85277b899e285ac21d4365f4c86fe232a7b3b89edc...,0x00000000000000000000000000000000000000000000...,0x5bcccb0233c118941d6a3163e63d46e88d27ada79eac...,0x0000000000000000000000000000000000000000,0,0,1320,0x,287981274,3736,2021-07-12 16:00:13,1,0xc38440,0x00000000000000000000000000000000000000000000...
99999,0x23d11041367252cd1191f56cd80a364d7a95e13a8842...,99999,0x0fe4523a2ebf1fe3428e4959e53572f7a60cfcf79460...,0x0000000000000000,,0x00000000000000000000000000000000000000000000...,0xccd374550b9b9c100633f961a96d9e1fe532c79079c6...,0x00000000000000000000000000000000000000000000...,0x5888a2d8862d29d9fc32242659e2706b3d3071580db9...,0x0000000000000000000000000000000000000000,0,0,1320,0x,287971921,3736,2021-07-12 16:00:13,1,0xc38440,0x00000000000000000000000000000000000000000000...
100000,0xcda6ee0a711052665540452ca33634c8a164efcec057...,100000,0x23d11041367252cd1191f56cd80a364d7a95e13a8842...,0x0000000000000000,,0x00000000000000000000000000000000000000000000...,0x29c5ab37d9c850c15377fb0d6311199dc9dd90f8fdd2...,0x00000000000000000000000000000000000000000000...,0xedec4c526c0558fe97deebfe1dd92621870f292d18b6...,0x0000000000000000000000000000000000000000,0,0,1320,0x,287990642,3736,2021-07-12 16:01:16,1,0xc38444,0x00000000000000000000000000000000000000000000...

In [44]:
sql = '''
select * from yarkin_arbitrum.transactions_raw LIMIT 10
'''
query_result, columns = chClient.execute(sql,with_column_types=True)
df = pd.DataFrame(query_result,columns=[tuple[0] for tuple in columns])
df

,hash,nonce,block_hash,block_number,transaction_index,from_address,to_address,value,gas,gas_price,input,block_timestamp
0,0x5f20ff43e91a85334d4b4d876089ab06270fd636c2d7...,0,0xb19bba5e4d767c845f1719a9e4b0a1e80b47db90c52c...,2,0,0x1c7d91ccbdbf378bac0f074678b09cb589184e4e,0x000000000000000000000000000000000000006d,0,10121,0,0x0ffd6650000000000000000000000000cce5c6cff61c...,2021-05-29 00:35:11
1,0xfc523577c087983847a69be1153626c2bc83f21b273d...,1,0x5b7be82ae165c66bdf727c54822ef9023440d4750e8a...,3,0,0x1c7d91ccbdbf378bac0f074678b09cb589184e4e,0x000000000000000000000000000000000000006b,0,10123,0,0xc6cabb4000000000000000000000000018a08f3ca72d...,2021-05-29 01:02:54
2,0x794c6075d6b7b5bfb1ab3fb84aa2821f98f1075dbe32...,2,0xa4e36737b18e5ffc517fa7cc2cdc28f82767f8f5a0c8...,4,0,0x1c7d91ccbdbf378bac0f074678b09cb589184e4e,0x000000000000000000000000000000000000006b,0,10133,0,0xcad462d4000000000000000000000000c12ba48c781f...,2021-05-29 01:05:59
3,0xd0ac15a46d63a7b28c58251d288061a4499466fe2cf6...,3,0xfa47fc069cd21353541f03bdf4416892ed1b60785b7f...,5,0,0x1c7d91ccbdbf378bac0f074678b09cb589184e4e,0x000000000000000000000000000000000000006b,0,10120,0,0x4290549e000000000000000000000000000000000000...,2021-05-29 01:07:22
4,0x20e71962e956753dea9c8e5ebb5e6e21d4ccf42d648f...,4,0xe6dfc9888ab1e65c1b9892a3898fdfa2159459a68826...,6,0,0x1c7d91ccbdbf378bac0f074678b09cb589184e4e,0x000000000000000000000000000000000000006b,0,112435,0,0x5b0b7f1e000000000000000000000000000000000000...,2021-05-29 01:08:31
5,0xaaed04c4bbc7aa5b23fc3dbda0dfdf543b3706882e1e...,5,0xb13e37838f237a2cccb11dfa887cb402faffef755ca7...,7,0,0x1c7d91ccbdbf378bac0f074678b09cb589184e4e,0x000000000000000000000000000000000000006b,0,25169,0,0x5b0b7f1e000000000000000000000000000000000000...,2021-05-29 01:12:32
6,0xa5053072d0be66f090a6436930ed1b6323530e1fe29a...,6,0x2af6a81eeca9840a5936b27150eb797e4856286522dc...,8,0,0x1c7d91ccbdbf378bac0f074678b09cb589184e4e,0x000000000000000000000000000000000000006b,0,10120,0,0xca4ba78c,2021-05-29 01:14:57
7,0xd906c8ffee4cd3e4812cbec00262f8d7f1f6e1b01c17...,7,0x7c85fabd83333240fc9fbbfa9809681cf528a8a23050...,9,0,0x1c7d91ccbdbf378bac0f074678b09cb589184e4e,0x000000000000000000000000000000000000006b,0,10132,0,0xc746c8f4000000000000000000000000f33ddb8eda68...,2021-05-29 01:18:45
8,0x53a1b331a943cbeb23859f798cf753869d89591c6020...,8,0x89f452a436be29df340c7de66cf3bfd8987680bba1aa...,10,0,0x1c7d91ccbdbf378bac0f074678b09cb589184e4e,0x000000000000000000000000000000000000006b,0,10143,0,0xc746c8f40000000000000000000000008f99b0b48b23...,2021-05-29 01:18:45
9,0xd6c6179388d86db9fbc00cf12b4b49a9f700cf98f1f3...,9,0x7207ea87e55ad0c1f18f12998fb391af6144665bde8d...,11,0,0x1c7d91ccbdbf378bac0f074678b09cb589184e4e,0x000000000000000000000000000000000000006b,0,10137,0,0xc746c8f4000000000000000000000000b4a3f907ec16...,2021-05-29 01:18:45

In [42]:
sql = '''
select count(*) from yarkin_arbitrum.transactions_raw
'''
query_result, columns = chClient.execute(sql,with_column_types=True)
query_result

[(99883,)]

In [43]:
sql = '''
select count(*) from yarkin_arbitrum.blocks_raw
'''
query_result, columns = chClient.execute(sql,with_column_types=True)
query_result

[(100001,)]